### ISSUE TITLE
FlutterUnionad.loadRewardVideoAd 的 mediaExtra 参数无效

### ISSUE THREAD

**Issue by GanYuhui** [gstory0404/flutter_unionad#108]
### 描述
> 使用激励视频 FlutterUnionad.loadRewardVideoAd 携带 mediaExtra: "token xxx" 参数，接口回掉的时候获取不到自定义参数，回调内容如下：

```
{ecpm=3117.639, extra=, mediation_rit=xxx, prime_rit=xxx, reward_amount=5, reward_name=解锁道具, reward_type=0, sign=36d2bbd88c071689ff4b462b326a68a37b7675e6f47aba33f094757582bb1a6f, trans_id=3f1eb80f-bb08-41ec-856c-a861519ac261, user_id=xxx}
```

### 设备版本
> 本地flutter版本为： 3.19.5、设备版本为：Android，

### 插件版本
> 插件版本为 2.0.0 

### 日志
> flutter 端截图：

![751717329939_ pic](https://github.com/gstory0404/flutter_unionad/assets/27198858/e1cded6e-9686-4888-a0f2-024d3772db5b)

服务端接受参数截图：

![Uploading 761717330082_.pic.jpg…]()

**Comment by GanYuhui** [comment]
服务端截图：
![image](https://github.com/gstory0404/flutter_unionad/assets/27198858/3dbda6a8-50ee-4be4-a3a4-dd19ddc95248)

**Comment by gstory0404** [comment]
普通广告还是融合广告？ @GanYuhui

**Comment by GanYuhui** [comment]
> 普通广告还是融合广告？ @GanYuhui

融合模式下

**Comment by gstory0404** [comment]
```
flutter_unionad:
  git:
     url: https://github.com/gstory0404/flutter_unionad.git
     ref: ee758963c9bbf68b844d06b4c94c7016f8a217f9
```
试一下这个 可以传递吗 @GanYuhui
