### ISSUE TITLE
信息流广告没有释放

### ISSUE THREAD

**Issue by 1mf2** [gstory0404/flutter_unionad#50]
我现在碰到的问题是在页面中集成了信息流广告，但是进入页面退出几次之后，视频广告就没法播放了，修改了下sdk的NativeExpressAdView中的dispose打印，但是没有看到打印，是不资源没有释放？

    override fun dispose() {
        if (mTTAd != null) {
            //调用destroy()方法释放
            Log.d(TAG, "NativeExpressAdView dispose")
            mTTAd!!.destroy();
        }
    }

**Comment by gstory0404** [comment]
```
flutter_unionad:
  git:
     url: https://github.com/gstory0404/flutter_unionad.git
     ref: 2144d675eb7ac479550aaecba3a9501cc9a73b5c
```
@1mf2 试一下
