### ISSUE TITLE
麻烦升级下kotlin-gradle-plugin版本，当前版本过低。

### ISSUE THREAD

**Issue by sven-xie** [gstory0404/flutter_unionad#97]
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher. The following dependencies do not satisfy the required version: project ':flutter_unionad' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.72

**Comment by gstory0404** [comment]
```
flutter_unionad:
  git:
     url: https://github.com/gstory0404/flutter_unionad.git
     ref: e363064152cecf94539c6d1a16296c77b937d026
```
引用dev分支的代码，主仓库下个版本合并 @sven-xie
